image: python:3.8.12-slim-buster  # TODO gitlab registry

# TODO reuse Makefile - "make sanity", and docker dind.

variables:
  # SC_HOST: https://10.5.11.30  # provide value in gitlab CI/CD settings
  SC_USERNAME: admin
  # SC_PASSWORD:  # provide value in gitlab CI/CD settings

stages:
  - test
  - build  # build collection tar.gz
  - deploy  # push collection tar.gz to galaxy

before_script:
  - pip3 install -r sanity.requirements -r test.requirements
  - apt update
  - apt install -y git shellcheck

coverage:
  stage: test
  image: python:3.8.12-slim-buster
  script:
    - pip install ansible-core==2.13.1
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/scale_computing/
    - cp -a ./  /work-dir/ansible_collections/scale_computing/hypercore
    - pushd /work-dir/ansible_collections/scale_computing/hypercore
    #
    # - ansible-test coverage erase --venv
    # Use venv, until we agree about dind - eventually we need to move to github anyway?
    - ansible-test units --coverage
    - ansible-test coverage html --requirements
    - ansible-test coverage report --omit 'tests/*' --show-missing
    - ls -al tests/output/reports/coverage
    - popd
    #
    # Move artifacts back to initial dir, so they can be collected by gitlab.
    - mkdir -p tests/output/reports/coverage
    - cp -a /work-dir/ansible_collections/scale_computing/hypercore/tests/output/reports/coverage/ tests/output/reports/coverage/
    - ls -al tests/output/reports/coverage
  artifacts:
    paths:
      - tests/output/reports/coverage
    expose_as: html_coverage
    expire_in: 10 week

sanity:
  stage: test
  image: python:3.8.12-slim-buster
  script:
    - pip install ansible-core==2.13.1
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/scale_computing/
    - cp -a ./  /work-dir/ansible_collections/scale_computing/hypercore
    - pushd /work-dir/ansible_collections/scale_computing/hypercore
    #
    # Same as "make sanity"
    # TODO reuse Makefile
    - black -t py27 --check --diff --color plugins tests/unit
    - flake8 --exclude tests/output/
    - ansible-test sanity

integration:
  stage: test
  image: python:3.8.12-slim-buster
  script:
    - pip install ansible-core==2.13.1
    # ansible-test needs special directory structure.
    - mkdir -p /work-dir/ansible_collections/scale_computing/
    - cp -a ./  /work-dir/ansible_collections/scale_computing/hypercore
    - pushd /work-dir/ansible_collections/scale_computing/hypercore
    #
    - |
      cat <<EOF >tests/integration/integration_config.yml
      # Generated by .gitlab-ci.yml
      sc_host: ${SC_HOST}
      sc_username: ${SC_USERNAME}
      sc_password: ${SC_PASSWORD}
      smb_server: ${SMB_SERVER}
      smb_share: ${SMB_SHARE}
      smb_username: ${SMB_USERNAME}
      smb_password: ${SMB_PASSWORD}
      EOF
    - cat tests/integration/integration_config.yml
    - ansible-test integration
