namespace: scale_computing
name: hypercore
version: 0.0.1
readme: README.md
authors:
- your name <example@domain.com>
description: your collection description
license: []
tags: []
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore:
- .idea
- .gitignore
- tests
# files used during local testing/building
- ansible.cfg
- examples
