---
namespace: scale_computing
name: hypercore
version: 1.1.0
readme: README.md
authors:
  - XLAB Steampunk <steampunk@xlab.si>
description: Manage Scale Computing HyperCore cluster
license_file: LICENSE
tags:
  - scale_computing
  - hypercore
  - infrastructure
  - virtualization
dependencies: {}
repository: https://github.com/ScaleComputing/HyperCoreAnsibleCollection
documentation: https://scalecomputing.github.io/HyperCoreAnsibleCollection-docs
homepage: https://github.com/ScaleComputing/HyperCoreAnsibleCollection
issues: https://github.com/ScaleComputing/HyperCoreAnsibleCollection/issues
build_ignore:
  - .idea
  - .gitignore
  - tests
  - docs
  # all this should be under hacking/ or similar
  - .ansible-lint
  - .flake8
  - ci-infra
  - DEVELOPMENT.md
  - docs.requirements
  - sanity.requirements
  - test.requirements
  - Makefile
  # files used during local testing/building
  - ansible.cfg
  - examples
  - .gitlab-ci.yml
