# Rename file to create_vm_playbook.yml? We have module vm_info, not VM_info.
# Can we put all sample playbooks into a single sub-directory?
- name: test iso_info module
  hosts: localhost
  environment:
    - SC_HOST: https://10.5.11.30
    - SC_USERNAME: admin
    - SC_PASSWORD: todo
  tasks:
  # ------------------------------------------------------
#  - name: List ISOs
#    scale_computing.hc3.iso_info:
#    register: iso_results
#
#  - name: output iso_results
#    debug:
#      var: iso_results
#
#  # ------------------------------------------------------
#  - name: List CentOS-7-x86_64-Minimal-1810.iso
#    scale_computing.hc3.iso_info:
#      name: CentOS-7-x86_64-Minimal-1810.iso
#    register: iso_results
#
#  - name: output iso_results
#    debug:
#      var: iso_results
#
  # ------------------------------------------------------
  - name: Delete Tiny Core Linux ISO
    scale_computing.hc3.iso:
      name: TinyCore-current.iso
      state: absent
    register: delete_result

  - name: output delete_result
    debug:
      var: delete_result

  # wget http://tinycorelinux.net/13.x/x86/release/TinyCore-current.iso -O /tmp/TinyCore-current.iso
  # echo not-really-iso > /tmp/TinyCore-current.iso
  - name: Create Tiny Core Linux ISO
    scale_computing.hc3.iso:
      name: TinyCore-current.iso
      state: present
      source: /tmp/TinyCore-current.iso
    register: create_result

  - name: output create_result
    debug:
      var: create_result

  # ------------------------------------------------------
  - name: List Tiny Core Linux ISO
    scale_computing.hc3.iso_info:
      name: TinyCore-current.iso
    register: iso_results

  - name: output iso_results
    debug:
      var: iso_results
