- name: import from URI
  hosts: localhost
  tasks:
  - name: import VM from URI
    scale_computing.hypercore.vm_import:
      cluster_instance:
        host: 'https://10.5.11.30'
        username: 'admin'
        password: 'admin'
      vm_name: XLAB-POST-TEST-import
      smb:
        server: IP-or-DNS-name-of-SMB-server
        path: /share/path/to/vms/demo-vm-exported-v0
        username: user
        password: pass
      cloud_init:
        user_data: |
          valid:
          - yaml: 1
          - expression: 2
        meta_data: "{{ lookup('file', 'cloud-init-user-data-example.yml') }}"
    register: testout

  - name: output the HTTP request results
    debug:
      var: testout
