- name: US 21 - As a user I want to be able to create, update and delete remote cluster to cluster replication connections to enable/disable replication
  hosts: localhost
  tasks:
  #TODO: uncomment when remote_cluster_info is implemented
  #- name: Get info about specific remote cluster
  #  scale_computing.hypercore.remote_cluster_info:
  #    remote_cluster: PUB4

  #TODO: uncomment when remote_cluster_info is implemented
  #- name: Get info about all remote clusters
  #  scale_computing.hypercore.remote_cluster_info:

  - name: Replicate demo-vm VM to DC2
    scale_computing.hypercore.vm_replication:
      vm_name: demo-vm
      remote_cluster: PUB4
      state: enabled  # choices [enabled|disabled|reenabled]

  - name: Pause replication for demo-vm
    scale_computing.hypercore.vm_replication:
      vm_name: demo-vm
      state: disabled # remote_cluster is not mandatory, since if it did not exist we do not need to create replication

  # Replication remote cluster was configured before, replication was only disabled.
  # Now it will be started again.
  - name: Reenable replication for demo-vm
    scale_computing.hypercore.vm_replication:
      vm_name: demo-vm
      state: reenabled

  - name: Get info about demo-vm replica in DC2
    scale_computing.hypercore.vm_replication_info:
      vm_name: demo-vm

  - name: Get info about all replicas
    scale_computing.hypercore.vm_replication_info:
