- name: US 11 - As a user I want to be able to add, update and remove VNICs so that I can reconfigure the networking
  hosts: localhost
  tasks:
  - name: Update existing NIC find by MAC address
    scale_computing.hc3.vm_nic:
      cluster_instance:
          host: 'https://10.5.11.30'
          username: 'admin'
          password: 'admin'
      vm_name: XLAB-demo-vm
      items:
        - vlan: 1
          mac: 7C:4C:58:C7:13:95
          vlan_new: 10
          mac_address_new: 01:23:45:67:89:ab
          type: virtio
      state: present
    loop:
