- name: test vm_nic module
  hosts: localhost  
  tasks:
  - name: Create nic #We leave MAC address blank, it auto-generates
    scale_computing.hypercore.vm_nic:
      cluster_instance:
        host: 'https://10.5.11.30'
        username: 'admin'
        password: 'admin'
      state: present #present, absent, set
      vm_name: 'XLAB-POST-TEST' #VM name, where NIC is being handled on
      #vm_uuid: '2e36ee02-5f97-4f93-a966-bde5beda796e' #can also pass VM UUID instead of name | either or
      items:
      - vlan: 15 #Default 0
        #new_vlan: 15 #This overwrites vlan, even during create
        #nic_uuid: 'acbd04bc-6486-4db4-bce3-065f3e92d3cb' #UUID of the NiC
        type: RTL8139 #RTL8139, INTEL_E1000, VIRTIO
        connected: true #Default true
    register: testout

  - name: output the HTTP request results
    debug:
      var: testout
