---
# Role configures HyperCore to state specified in scale_computing_hypercore_cluster_config.
# Partial (re)configuration is possible - missing configuration values are not reconfigured.
# If you need to remove some configuration, you can:
# - provide explicit empty value ("" or [] or {}) for given configuration entry
# - or call corresponding plugin with state=absent

- name: Set cluster name
  scale_computing.hypercore.cluster_name:
    name_new: "{{ scale_computing_hypercore_cluster_config.name }}"
  when: scale_computing_hypercore_cluster_config.name | default(False)

- name: Set registration data
  scale_computing.hypercore.registration:
    company_name: "{{ scale_computing_hypercore_cluster_config.registration.company_name }}"
    contact: "{{ scale_computing_hypercore_cluster_config.registration.contact }}"
    phone: "{{ scale_computing_hypercore_cluster_config.registration.phone }}"
    email: "{{ scale_computing_hypercore_cluster_config.registration.email }}"
    state: present
  when: scale_computing_hypercore_cluster_config.registration | default(False)

- name: Set DNS servers configuration
  scale_computing.hypercore.dns_config:
    dns_servers: "{{ scale_computing_hypercore_cluster_config.dns.server_ips | default(omit) }}"
    state: set
  when:
    - scale_computing_hypercore_cluster_config.dns | default(False)
    - '"server_ips" in scale_computing_hypercore_cluster_config.dns'
    - scale_computing_hypercore_cluster_config.dns.server_ips is not none

- name: Set DNS search_domains configuration
  scale_computing.hypercore.dns_config:
    dns_servers: "{{ scale_computing_hypercore_cluster_config.dns.server_ips | default(omit) }}"
    search_domains: "{{ scale_computing_hypercore_cluster_config.dns.search_domains | default(omit) }}"
    state: set
  when:
    - scale_computing_hypercore_cluster_config.dns | default(False)
    - '"search_domains" in scale_computing_hypercore_cluster_config.dns'
    - scale_computing_hypercore_cluster_config.dns.search_domains is not none

- name: Set OIDC configuration
  scale_computing.hypercore.oidc_config:
    client_id: "{{ scale_computing_hypercore_cluster_config.oidc.client_id }}"
    shared_secret: "{{ scale_computing_hypercore_cluster_config.oidc.shared_secret | default(omit) }}"
    certificate: "{{ scale_computing_hypercore_cluster_config.oidc.certificate | default(omit) }}"
    config_url: "{{ scale_computing_hypercore_cluster_config.oidc.config_url }}"
    scopes: "{{ scale_computing_hypercore_cluster_config.oidc.scopes }}"
  when: scale_computing_hypercore_cluster_config.oidc | default(False)

- name: Set time server
  scale_computing.hypercore.time_server:
    source: "{{ scale_computing_hypercore_cluster_config.time_server }}"
  when: scale_computing_hypercore_cluster_config.time_server | default(False)

- name: Set time zone
  scale_computing.hypercore.time_zone:
    zone: "{{ scale_computing_hypercore_cluster_config.time_zone }}"
  when: scale_computing_hypercore_cluster_config.time_zone | default(False)

- name: Set SMTP configuration
  scale_computing.hypercore.smtp:
    server: "{{ scale_computing_hypercore_cluster_config.smtp.server }}"
    port: "{{ scale_computing_hypercore_cluster_config.smtp.port }}"
    use_ssl: "{{ scale_computing_hypercore_cluster_config.smtp.use_ssl | default(omit) }}"
    auth_user: "{{ scale_computing_hypercore_cluster_config.smtp.auth_user | default(omit) }}"
    auth_password: "{{ scale_computing_hypercore_cluster_config.smtp.auth_password | default(omit) }}"
    from_address: "{{ scale_computing_hypercore_cluster_config.smtp.from_address | default(omit) }}"
  when: scale_computing_hypercore_cluster_config.smtp | default(False)

- name: Reconfigure email alert recipients
  when:
    - '"email_alerts" in scale_computing_hypercore_cluster_config'
    - |
      scale_computing_hypercore_cluster_config.email_alerts or
      scale_computing_hypercore_cluster_config.email_alerts == []
  block:
    - name: Get old email alert recipients
      scale_computing.hypercore.email_alert_info:
      register: cluster_config_email_alert_info_result

    - name: Remove old email alerts
      scale_computing.hypercore.email_alert:
        email: "{{ email_alert_recipient.email }}"
        state: absent
      loop: "{{ cluster_config_email_alert_info_result.records }}"
      loop_control:
        loop_var: email_alert_recipient
      when: email_alert_recipient.email not in scale_computing_hypercore_cluster_config.email_alerts

    - name: Set new email alerts
      scale_computing.hypercore.email_alert:
        email: "{{ email_address }}"
        state: present
      loop: "{{ scale_computing_hypercore_cluster_config.email_alerts or [] }}"
      loop_control:
        loop_var: email_address

- name: Reconfigure syslog servers
  when:
    - '"syslog_servers" in scale_computing_hypercore_cluster_config'
    - |
      scale_computing_hypercore_cluster_config.syslog_servers or
      scale_computing_hypercore_cluster_config.syslog_servers == []
  block:
    - name: Get old syslog servers
      scale_computing.hypercore.syslog_server_info:
      register: cluster_config_syslog_server_info_result

    - name: Remove old syslog servers
      scale_computing.hypercore.syslog_server:
        host: "{{ syslog_server.host }}"
        state: absent
      loop: "{{ cluster_config_syslog_server_info_result.records }}"
      loop_control:
        loop_var: syslog_server
      when: syslog_server.host not in (scale_computing_hypercore_cluster_config.syslog_servers | map(attribute='host') | list)

    - name: Set new syslog servers
      scale_computing.hypercore.syslog_server:
        host: "{{ syslog_server.host }}"
        port: "{{ syslog_server.port | default(omit) }}"
        protocol: "{{ syslog_server.protocol | default(omit) }}"
        state: present
      loop: "{{ scale_computing_hypercore_cluster_config.syslog_servers or [] }}"
      loop_control:
        loop_var: syslog_server
