---
#  ------------
# | Pseudocode
#  ------------
# 1. available_updates = get_available_updates()
# 2. next_update_index = 0
# 3. while available_updates:
# 4.    update = available_updates[next_update_index]
# 5.    status = get_update_status(update)
# 6.    if status != "IN PROGRESS"
# 7.        apply_update(update)
# 8.    if status == "COMPLETE":
# 9.        next_update_index += 1

- name: Get available updates
  scale_computing.hypercore.update_version_info:
  register: available_updates

- name: Show available updates
  ansible.builtin.debug:
    var: available_updates

- name: Get all available running VMs
  scale_computing.hypercore.vm_info:
  register: vms

- name: Update
  block:
    - name: Shutdown all running VMs
      include_tasks: shutdown_vms.yml

    # - name: Update single-node system
    #   include_tasks: update.my
    #   loop: "{{ available_updates }}"

    - name: Restart previously running VMs
      include_tasks: restart_vms.yml
  when: available_updates

# - name: Shutdown all running VMs
#   include_tasks:
#
# - name: Update single-node system
#   include_tasks: update.yml
#   when: available_updates
