---
- name: Get available updates
  scale_computing.hypercore.api:
    action: get
    endpoint: /rest/v1/Update
  register: available_updates

- name: Show available updates
  ansible.builtin.debug:
    var: available_updates

- name: Update single-node system
  include_tasks: update.yml
  when: available_updates
