---
- name: Check update status on HC3
  block:
    - name: Increment version_update_single_node_retry_count
      ansible.builtin.set_fact:
        version_update_single_node_retry_count: >-
          "{{
          0 if version_update_single_node_retry_count is undefined
          else version_update_single_node_retry_count | int + 1
          }}"

    # Do not remove this magic delay.
    # Likely sometimes we query for update status before HyperCore actually started the update.
    # Then we get back something like "update completed", but this refers to some older update.
    # More testing needed before we can replace this with something smarter.
    # What could be smarter:
    # - look at version_update_status_info.build_id,
    #   wait until it is equal to version/build_id we are updating to.
    # - remember version_update_status_info might return some bogus data if HyperCore was never updated.
    # Why:
    # - testing this role even in dry-run mode will take at least 20*60 sec. One lunch per test.
    - name: Pause before checking update status - checks will report FAILED-RETRYING until update COMPLETE/TERMINATED
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost

    - name: Check update status - will report FAILED-RETRYING until update COMPLETE/TERMINATED
      scale_computing.hypercore.version_update_status_info:
      register: version_update_single_node_update_status
      until: >-
        version_update_single_node_update_status.record != None and
        (
          version_update_single_node_update_status.record.update_status == "COMPLETE" or
          version_update_single_node_update_status.record.update_status == "TERMINATING"
        )
      retries: 100
      delay: 30
      ignore_unreachable: true

  rescue:
    - name: Fail if retries reached 20
      ansible.builtin.fail:
        msg: Maximum retries of grouped tasks reached
      when: version_update_single_node_retry_count | int == 20

    - name: Log
      ansible.builtin.debug:
        msg: Update status check failed due to server down / restart - retrying

    - name: Check update status again
      ansible.builtin.include_tasks: update_status_check.yml # Recursion
