---
- name: Check update status on HC3
  block:
    - name: Increment version_update_single_node_retry_count
      ansible.builtin.set_fact:
        version_update_single_node_retry_count: >-
          "{{
          0 if version_update_single_node_retry_count is undefined
          else version_update_single_node_retry_count | int + 1
          }}"

    - name: Check update status - will report FAILED-RETRYING until update COMPLETE/TERMINATED
      scale_computing.hypercore.version_update_status_info:
      register: version_update_single_node_update_status
      until: >-
        version_update_single_node_update_status.record != None and
        (
          version_update_single_node_update_status.record.update_status == "COMPLETE" or
          version_update_single_node_update_status.record.update_status == "TERMINATING"
        )
      retries: 100
      delay: 30
      ignore_unreachable: true

  rescue:
    - name: Fail if retries reached 20
      ansible.builtin.fail:
        msg: Maximum retries of grouped tasks reached
      when: version_update_single_node_retry_count | int == 20

    - name: Log
      ansible.builtin.debug:
        msg: Update status check failed due to server down / restart - retrying

    - name: Check update status again
      ansible.builtin.include_tasks: update_status_check.yml # Recursion
