---
# With future version_update module
- name: Update HC3
  block:
    - name: Check progress
      scale_computing.hypercore.version_update_status_info:
      register: update_status

    - name: Update one
      scale_computing.hypercore.version_update:
      icos_version: "{{ item.uuid }}"
      when: update_status != "COMPLETE"

    - name: Show update status
      ansible.builtin.debub:
        var: update_status
  when: available_updates
  always:
  # loop: "{{ available_updates.records }}"
  # TODO: Add progress check
  # - wait for update to finish, then move on to next update
