---
version: "3.9"
services:
  vpnclient:
    build: .
    # image: dperson/openvpn-client
    volumes:
      - ./config:/vpn
    # cap_add:
    #  - NET_ADMIN
    #  - SYS_ADMIN
    privileged: true
    ports:
      - 8443:8443
    environment:
      - EXTRA_BACKGROUND_CMD=socat TCP-LISTEN:8443,fork,reuseaddr TCP:10.5.11.30:443
    restart: on-failure
volumes:
  config:
