---
# Run as:
# ansible-playbook -i examples/vm_snapshot_clone_update/inventory.yml -e @examples/vm_snapshot_clone_update/vars.yml examples/vm_snapshot_clone_update/main.yml
- name: Create VM
  hosts: localhost # Do I need this??
  connection: local
  gather_facts: false
  vars:
    iso_url: https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
    iso_filename: "{{ iso_url | split('/') | last }}"
  tasks:
    - name: Create SSH key
      ansible.builtin.include_tasks: 01_create_ssh_key.yml
    - name: Upload ISO image
      ansible.builtin.include_tasks: 02_upload_iso.yml
    - name: Create source VM
      ansible.builtin.include_tasks: 03_create_source_vm.yml

- name: Inject data into VM
  hosts: "{{ source_vm_name }}"
  tasks:
    - name: Setup source VM
      ansible.builtin.include_tasks: 04_setup_source_vm.yml

    - meta: end_play

# --------------------------------------------------------------

    - name: Create vm-focal-fossa snapshot
      scale_computing.hypercore.vm_snapshot:
        state: present
        vm_name: "{{ vm_created.record.0.vm_name }}"
        label: snap-1
      register: vm_created_snapshot

    - name: Clone vm-focal-fossa snapshot into vm-focal-fossa-clone
      scale_computing.hypercore.vm_clone:
        vm_name: vm-focal-fossa-clone
        source_vm_name: vm-focal-fossa  # latest snapshot will be cloned
        # tags:
        #   - new tag
      register: vm_cloned
    - ansible.builtin.assert:
        that:
          - vm_cloned is changed
          - vm_cloned.msg == "Virtual machine - vm-focal-fossa - cloning complete to - vm-focal-fossa-clone."

    - name: Retrieve vm_cloned
      scale_computing.hypercore.vm_info:
        vm_name: vm_cloned
      register: result # this has no ip, what to add to inventory?

    # - name: Upgrade the OS (apt-get dist-upgrade) # on which host? new host needs to be added?
    #   ansible.builtin.apt:
    #     upgrade: dist

    # ansible_user                 = "ubuntu",
    # ansible_ssh_private_key_file = "~/.ssh/id_rsa",
    # ansible_python_interpreter   = "/usr/bin/python3",


    # Use vm module output, syntax valid until release < 3.0.0
    - name: Show VM {{ vm_name }} vCPU count - syntax valid until release < 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.0.vcpu }} vCPUs -
          syntax valid until release < 3.0.0

    # Use vm module output, new syntax, valid after release >= 3.0.0
    - name: Show VM {{ vm_name }} vCPU count - syntax valid after release >= 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.vcpu }} vCPUs -
          syntax valid after release >= 3.0.0
      when: false  # 3.0.0 is not yet released
