---
# Run as:
#
- name: Create VM
  hosts: localhost # Do I need this??
  connection: local
  gather_facts: false
  vars:
    # VM to create, install nginx and "deploy" a simple static web page.
    source_vm_name: demo-snapshot-source
    # VM snapshot with label source_snapshot_label will be craete from VM source_vm_name.
    source_snapshot_label: demo-snapshot-label-0
    # Old snapshot with same label will be removed, and new one created.
    source_snapshot_force_recreate: True
    # A VM with name cloned_vm_name will be created from source_snapshot_label.
    cloned_vm_name: demo-snapshot-clone
    # SSH key to create and use
    demo_ssh_key_path: demo_ssh_key

    # image_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    iso_url: https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
    iso_filename: "{{ iso_url | split('/') | last }}"

  tasks:
    - name: Create SSH key
      ansible.builtin.include_tasks: 01_create_ssh_key.yml
    - name: Upload ISO image
      ansible.builtin.include_tasks: 02_upload_iso.yml
    - name: Create source VM
      ansible.builtin.include_tasks: 03_create_source_vm.yml

    - meta: end_play



    - name: Create vm-focal-fossa snapshot
      scale_computing.hypercore.api:
        action: post
        endpoint: /rest/v1/VirDomainSnapshot
        data:
          domainUUID: "{{ vm_created.record.0.uuid }}"
          label: snap-1
      register: vm_created_snapshot
    
    - name: Wait for the snapshot
      scale_computing.hypercore.task_wait:
        task_tag: "{{ vm_created_snapshot.record }}"
    
    - name: Clone vm-focal-fossa snapshot into vm-focal-fossa-clone
      scale_computing.hypercore.vm_clone:
        vm_name: vm-focal-fossa-clone
        source_vm_name: vm-focal-fossa  # latest snapshot will be cloned
        # tags:
        #   - new tag
      register: vm_cloned
    - ansible.builtin.assert:
        that:
          - vm_cloned is changed
          - vm_cloned.msg == "Virtual machine - vm-focal-fossa - cloning complete to - vm-focal-fossa-clone."

    - name: Upgrade the OS (apt-get dist-upgrade) # on which host? new host needs to be added?
      ansible.builtin.apt:
        upgrade: dist

    # ansible_user                 = "ubuntu",
    # ansible_ssh_private_key_file = "~/.ssh/id_rsa",
    # ansible_python_interpreter   = "/usr/bin/python3",


    # Use vm module output, syntax valid until release < 3.0.0
    - name: Show VM {{ vm_name }} vCPU count - syntax valid until release < 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.0.vcpu }} vCPUs -
          syntax valid until release < 3.0.0

    # Use vm module output, new syntax, valid after release >= 3.0.0
    - name: Show VM {{ vm_name }} vCPU count - syntax valid after release >= 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.vcpu }} vCPUs -
          syntax valid after release >= 3.0.0
      when: false  # 3.0.0 is not yet released
