#cloud-config
# NOTE: The cloud-init user-data MUST begin with be "#cloud-config" string!
#
# Tested with Ubuntu 20.04.4 LTS server ISO image
# https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
# To manually test cloud-init ISO image, create one with commands:
#   cp cloud-init-user-data-example.yml /tmp/user-data
#   echo -n '' > /tmp/meta-data
#   sudo cloud-localds /var/lib/libvirt/boot/cloud-init-min.iso /tmp/user-data /tmp/meta-data
autoinstall:
    version: 1
    locale: en_US
    storage:
        layout:
            name: lvm
        swap:
            filename: /swap.img
            size: 100M
    network:
        network:
            version: 2
            renderer: networkd
            ethernets:
                # name can be different - eno1, eth0, enp1s0, ...
                enp1s0:
                    addresses:
                        - 192.168.122.30/24
                    gateway4: 192.168.122.1
                    nameservers:
                        addresses: ['192.168.122.1']
    ssh:
        install-server: true
        authorized-keys: ['ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE8SNzKoqj89P6Z9kiYEhgbDogY0Y7YXSS68W2B5b2u7 justin_cinkelj@jcnuc']
        allow-pw: false
    user-data:
        hostname: mytestvm
        disable_root: false
        users:
            -
                name: myuser
                # myuserp password
                passwd: >-
                    $6$.igLISmqzw4hTyS4$4zAx6zWl5FnD3s8YSmn/UOvo0QDg6GuHJcmiB7EYwnbDn9SgZxvmyDeWN4WY6LRFDdChExALqyGfiPHmK1w.j/
                shell: /bin/bash
                lock_passwd: false
                primary_group: myuser
                groups: 'adm, cdrom, sudo, dip, plugdev, netdev, lxd'
                ssh_authorized_keys: ['ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE8SNzKoqj89P6Z9kiYEhgbDogY0Y7YXSS68W2B5b2u7 justin_cinkelj@jcnuc']
        ssh:
            disable_root: false
        write_files:
            -
                content: |
                    [Time]
                    NTP=0.pool.ntp.org
                path: /etc/systemd/timesyncd.conf.d/60-mytestvm.conf
            -
                content: |
                    PasswordAuthentication no
                path: /etc/ssh/sshd_config.d/60-mytestvm.conf

    updates: security
    packages:
        - ntpdate
        # nice to have utils
        - bwm-ng
        - sysstat
        - net-tools
        - vim
        - iftop
        - tmux
    early-commands: []
    late-commands:
        # rootp password
        - sed -i 's|^root:\*:|root:\$6\$2NMUxRBiMjQg.iwJ\$eyTXnMseF.N5a62F6rZnKJVGd72HPW6F.KGcq9oFNz7fvMzV5FOvYPkxf..hGxRChhS9CkICOdWSvV.Ldmq871:|' /target/etc/shadow
        - poweroff
