---
- name: Example dns_config_info module
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    # ------------------------------------------------------
    - name: List DNS config entries
      scale_computing.hypercore.dns_config_info:
      register: dns_config_info_results

    - name: Show all DNS config entries
      debug:
        var: dns_config_info_results
