---
- name: Example dns_config module
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    # ------------------------------------------------------
    - name: Add to DNS configuration records
      scale_computing.hypercore.dns_config:
        search_domains:
          - example_dns_1
          - example_dns_2
          - example_dns_3
          - do_not_need_this_dns
        dns_servers:
          - 1.2.3.4
          - 5.6.7.8
        state: present

    # ------------------------------------------------------
    - name: Delete DNS configuration records
      scale_computing.hypercore.dns_config:
        search_domains:
          - do_not_need_this_dns
        dns_servers:
          - 5.6.7.8
        state: absent
