---
- name: Upload ISO image from http link to HyperCore
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    iso_url: http://tinycorelinux.net/13.x/x86/release/TinyCore-current.iso
    iso_filename: "{{ iso_url | split('/') | last }}"
    iso_remove_old_image: false

  tasks:
    # ------------------------------------------------------
    - name: Download ISO from URL - {{ iso_filename }}
      ansible.builtin.get_url:
        url: "{{ iso_url }}"
        dest: /tmp/{{ iso_filename }}
        mode: "0644"

    - name: (Optionally) remove existing ISO from HyperCore - {{ iso_filename }}
      scale_computing.hypercore.iso:
        name: "{{ iso_filename }}"
        source: /tmp/{{ iso_filename }}
        state: absent
      when: iso_remove_old_image

    # ------------------------------------------------------
    - name: Upload ISO to HyperCore - {{ iso_filename }}
      scale_computing.hypercore.iso:
        name: "{{ iso_filename }}"
        source: /tmp/{{ iso_filename }}
        state: present
      register: uploaded_iso

    # Use iso module output, old syntax, valid until release < 3.0.0
    - name: Show upload result for ISO - deprecated syntax - {{ iso_filename }}
      ansible.builtin.debug:
        msg: The uploaded_iso size={{ uploaded_iso.results.0.size }} - deprecated syntax

    # Use iso module output, new syntax, valid after release >= 1.2.0
    - name: Show upload result for ISO {{ iso_filename }}
      ansible.builtin.debug:
        msg: The uploaded_iso size={{ uploaded_iso.record.size }}

    # ------------------------------------------------------
    - name: Get info about specific ISO image - {{ iso_filename }}
      scale_computing.hypercore.iso_info:
        name: "{{ iso_filename }}"
      register: iso_results

    - name: Show info about ISO {{ iso_filename }}
      ansible.builtin.debug:
        var: iso_results.records[0]
