---
- name: Example oidc_config module and oidc_config_info module
  hosts: localhost
  connection: local
  gather_facts: false
  # We do not want to reconfigure cluster with bogus example values.
  # OIDC cannot be removed once setup!
  check_mode: true

  vars:
    oidc_client_id: your_client_id
    oidc_shared_secret: your_client_secret
    oidc_config_url: https://login.microsoftonline.com/your_uuid/v2.0/.well-known/openid-configuration
    oidc_scopes: "openid+profile"

  tasks:
    # ------------------------------------------------------
    - name: List oidc config
      scale_computing.hypercore.oidc_config_info:
      register: oidc_config_info_results

    - name: Show oidc config entries
      debug:
        var: oidc_config_info_results

    - name: Create or update OIDC config
      scale_computing.hypercore.oidc_config:
        client_id: "{{ oidc_client_id }}"
        shared_secret: "{{ oidc_shared_secret }}"
        config_url: "{{ oidc_config_url }}"
        scopes: "{{ oidc_scopes }}"

    - name: List updated oidc config
      scale_computing.hypercore.oidc_config_info:
      register: oidc_config_info_results

    - name: Show updated oidc config entries
      debug:
        var: oidc_config_info_results
