---
- name: List SMTP configuration
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: List SMTP Configuration
      scale_computing.hypercore.smtp_info:
      register: smtp_info

    - name: Show SMTP configuration
      ansible.builtin.debug:
        msg: "{{ smtp_info }}"
