---
- name: Example time_server_info module
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get current Time Server
      scale_computing.hypercore.time_server_info:
      register: time_server_info

    - name: Show NTP time server configuration
      ansible.builtin.debug:
        msg: "{{ time_server_info }}"
