---
- name: Example time_zone_info module
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get current Time Zone
      scale_computing.hypercore.time_zone_info:
      register: time_zone_info
    - ansible.builtin.debug:
        msg: "{{ time_zone_info }}"
