---
- name: Update a HyperCore single-node system
  hosts: localhost
  connection: local
  gather_facts: false
  # Comment out check_mode=true if you really want to start update.
  check_mode: true

  vars:
    desired_version: 9.2.17.211525

  tasks:
    - name: Show desired_version
      ansible.builtin.debug:
        msg: Desired HyperCore version for host {{ lookup('ansible.builtin.env', 'SC_HOST') }} is {{ desired_version }}.

    - name: Get host's time zone
      scale_computing.hypercore.time_zone_info:
      register: time_zone_info

    - name: Check time zone is configured
      ansible.builtin.assert:
        fail_msg: Time zone is not set on the host
        that:
          - time_zone_info.record

    - name: Check that local time meets required time interval
      ansible.builtin.include_role:
        name: scale_computing.hypercore.check_local_time
      vars:
        check_local_time_time_zone: "{{ time_zone_info.record.zone }}"
        check_local_time_time_interval: 22:00-6:00

    - name: Update HyperCore single-node system to a desired version
      ansible.builtin.include_role:
        name: scale_computing.hypercore.version_update_single_node
      vars:
        version_update_single_node_desired_version: "{{ desired_version }}"
