---
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: demo-vm

  tasks:
    - name: Create VM {{ vm_name }}
      scale_computing.hypercore.vm:
        vm_name: "{{ vm_name }}"
        memory: "{{ '1 GB' | human_to_bytes }}"
        vcpu: 2
        disks:
          - type: virtio_disk
            disk_slot: 0
            size: "{{ '10 GB' | human_to_bytes }}"
        nics:
          - type: virtio
            vlan: 10
        state: present
        # os_other or os_windows_server_2012
        operating_system: os_other
      register: vm_result

    - name: Show the info about VM {{ vm_name }}
      ansible.builtin.debug:
        var: vm_result

    # Use vm module output, syntax valid until release < 3.0.0
    - name: Show VM vCPU count - syntax valid until release < 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.0.vcpu }} vCPUs -
          syntax valid until release < 3.0.0

    # Use vm module output, new syntax, valid after release >= 3.0.0
    - name: Show VM vCPU count - syntax valid after release >= 3.0.0
      ansible.builtin.debug:
        msg: >-
          VM {{ vm_name }} has {{ vm_result.record.vcpu }} vCPUs -
          syntax valid after release >= 3.0.0
      when: false  # 3.0.0 is not yet released
