---
- name: Show replication settings for a specific VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: demo-vm

  tasks:
    - name: Get info about VM {{ vm_name }}
      scale_computing.hypercore.vm_info:
        vm_name: "{{ vm_name }}"
      register: vm_info_result

    - name: Show the info about VM {{ vm_name }}
      ansible.builtin.debug:
        var: vm_info_result
