---
- name: Configure VM with a two NICs with specific VLANs
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: demo-vm
    vlan_a: 10
    vlan_b: 11

  tasks:
    - name: Configure VM {{ vm_name }} with 2 NICs, VLANs {{ vlan_a }} and {{ vlan_b }}
      scale_computing.hypercore.vm_nic:
        vm_name: "{{ vm_name }}"
        items:
          - vlan: "{{ vlan_a }}"
          - vlan: "{{ vlan_b }}"
        state: set
      register: vm_nic_result

    - name: Show the VM {{ vm_name }} new NIC state
      ansible.builtin.debug:
        var: vm_nic_result

    - name: Show VM {{ vm_name }} new NIC VLANs
      ansible.builtin.debug:
        msg: The configured VLANs are {{ vm_nic_result.records | map(attribute="vlan") }}
