---
- name: Show replication settings for a specific VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: demo-vm

  tasks:
    - name: Get replication info for VM {{ vm_name }}
      scale_computing.hypercore.vm_replication_info:
        vm_name: "{{ vm_name }}"
      register: replication_info_result

    - name: Show the replication info status of VM {{ vm_name }}
      ansible.builtin.debug:
        var: replication_info_result
