---
- name: Show available snapshots by a desired filter
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: demo-vm
    snapshot_serial: 123
    snapshot_label: snapshot-label

  tasks:
    - name: List all VM snapshots on HyperCore API
      scale_computing.hypercore.vm_snapshot_info:
      register: vm_snapshot

    - name: List all VM snapshots on HyperCore API with label="{{ snapshot_label }}"
      scale_computing.hypercore.vm_snapshot_info:
        label: "{{ snapshot_label }}"
      register: vm_snapshot

    - name: List all VM snapshots on HyperCore API with vm_name="{{ vm_name }}"
      scale_computing.hypercore.vm_snapshot_info:
        vm_name: "{{ vm_name }}"
      register: vm_snapshot

    - name: List all VM snapshots on HyperCore API with serial="{{ snapshot_serial }}"
      scale_computing.hypercore.vm_snapshot_info:
        serial: "{{ snapshot_serial }}"
      register: vm_snapshot

    - name: >-
        List all VM snapshots on HyperCore API with
        [vm_name, label, serial]={{ [vm_name, snapshot_label, snapshot_serial] }}
      scale_computing.hypercore.vm_snapshot_info:
        vm_name: "{{ vm_name }}"
        label: "{{ snapshot_label }}"
        serial: "{{ snapshot_serial }}"
      register: vm_snapshot
