---
# Run as
# ansible-playbook -i localhost, examples/url2template/template2vm.yml -v
- name: Create template VM from disk image URL
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image_url: https://cloud-images.ubuntu.com/releases/22.04/release-20240416/ubuntu-22.04-server-cloudimg-amd64.img
    machine_type: BIOS

  roles:
    - role: scale_computing.hypercore.url2template
      vars:
        url2template_image_url: "{{ image_url }}"
        url2template_vm_name: "{{ vm_name | default(image_url | split('/') | last) }}"
        url2template_machine_type: "{{ machine_type }}"
        url2template_operating_system: os_other
