---
- name: Check if local time is in time interval (run check_local_time.py)
  ansible.builtin.script:
    executable: "{{ ansible_python_interpreter | default(ansible_playbook_python) }}"
    cmd: check_local_time.py "{{ check_local_time_time_zone }}" "{{ check_local_time_time_interval }}"
  register: check_local_time_output

- name: Assert that local time is in time interval
  ansible.builtin.assert:
    fail_msg: "Local time for time zone {{ check_local_time_time_zone }} is not in required time interval {{ check_local_time_time_interval }}"
    success_msg: "Local time for time zone {{ check_local_time_time_zone }} is in required time interval {{ check_local_time_time_interval }}"
    that:
      - check_local_time_output.stdout_lines[0] == "True"
  register: check_local_time_result

- name: Set fact to use in tests
  ansible.builtin.set_fact:
    check_local_time_msg: "{{ check_local_time_result.msg }}"
