---
- environment:
    SC_HOST: "{{ sc_host }}"
    SC_USERNAME: "{{ sc_username }}"
    SC_PASSWORD: "{{ sc_password }}"
    SC_TIMEOUT: "{{ sc_timeout }}"

  block:
    - name: Get Time Zone
      scale_computing.hypercore.time_zone_info:
      register: time_zone

    - name: Check if local time is in time interval (run check_local_time.py)
      ansible.builtin.script:
        executable: python
        cmd: check_local_time.py "{{ time_zone }}" "{{ time_interval }}"
      register: local_time_output
    
    - name: Assert that local time is in time interval
      ansible.builtin.assert:
        msg: Local time is not in required time interval
        that:
         - local_time_output.stdout_lines[0] == "True"