- name: Download ISO from URL - {{ iso_filename }}
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    dest: /tmp/{{ iso_filename }}
    mode: "0644"

- name: Upload ISO to HyperCore - {{ iso_filename }}
  scale_computing.hypercore.iso:
    name: "{{ iso_filename }}"
    source: /tmp/{{ iso_filename }}
    state: present
