- name: Report uptime
  ansible.builtin.command: uptime

- name: Upload index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

# Firewall needs to be opened
- name: Check index.html is served to external host
  ansible.builtin.uri:
    url: "http://{{ hostvars[cloned_vm_name]['ansible_host'] }}"
    return_content: true
  delegate_to: localhost
  register: url_data
  failed_when: "'test-html-for-scale-computing-demo' not in url_data.content"
