---
# Run as:
# ansible-playbook -i examples/vm_os_upgrade/inventory.yml -e @examples/vm_os_upgrade/vars.yml examples/vm_os_upgrade/main.yml
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create SSH key
      ansible.builtin.include_tasks: 01_create_ssh_key.yml
    - name: Upload ISO image
      ansible.builtin.include_tasks: 02_upload_iso.yml
    - name: Create source VM
      ansible.builtin.include_tasks: 03_create_source_vm.yml

- name: Inject data into VM
  hosts: "{{ source_vm_name }}"
  tasks:
    - name: Setup source VM
      ansible.builtin.include_tasks: 04_setup_source_vm.yml

- name: Clone VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create clone from source VM
      ansible.builtin.include_tasks: 05_clone_from_source.yml

- name: Upgrade all the packages and kernel before upgrading the distribution version
  hosts: "{{ cloned_vm_name }}"
  gather_facts: true
  tasks:
    - name: Distribution version
      ansible.builtin.debug: msg="{{ ansible_distribution_version}}"
    - name: Upgrade all the packages and kernel before upgrading the distribution version (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

- name: Reboot cloned VM
  hosts: localhost
  connection: local
  tasks:
    - name: Reboot VM
      ansible.builtin.include_tasks: 06_reboot_cloned_vm.yml

- name: Upgrade distribution version
  hosts: "{{ cloned_vm_name }}"
  gather_facts: true
  tasks:
    - name: Upgrade distribution version
      ansible.builtin.shell: do-release-upgrade -f DistUpgradeViewNonInteractive

- name: Reboot cloned VM
  hosts: localhost
  connection: local
  tasks:
    - name: Reboot VM
      ansible.builtin.include_tasks: 06_reboot_cloned_vm.yml

- name: Check distribution version and index.html
  hosts: "{{ cloned_vm_name }}"
  gather_facts: true
  tasks:
    - name: New Distribution version
      ansible.builtin.debug: msg="{{ ansible_distribution_version}}"
    - name: Check index.html is served to external host
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}"
        return_content: true
      delegate_to: localhost
      register: url_data
      failed_when: "'test-html-for-scale-computing-demo' not in url_data.content"
