---
# Run as:
# ansible-playbook -i examples/vm_os_upgrade/inventory.yml -e @examples/vm_os_upgrade/vars.yml examples/vm_os_upgrade/main.yml
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    iso_url: https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
    iso_filename: "{{ iso_url | split('/') | last }}"
  tasks:
    - name: Create SSH key
      ansible.builtin.include_tasks: 01_create_ssh_key.yml
    - name: Upload ISO image
      ansible.builtin.include_tasks: 02_upload_iso.yml
    - name: Create source VM
      ansible.builtin.include_tasks: 03_create_source_vm.yml

- name: Inject data into VM
  hosts: "{{ source_vm_name }}"
  tasks:
    - name: Setup source VM
      ansible.builtin.include_tasks: 04_setup_source_vm.yml

- name: Clone VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create clone from source VM
      ansible.builtin.include_tasks: 05_clone_from_source.yml

- name: Upgrade OS on cloned vm as a root
  hosts: "{{ cloned_vm_name }}"
  gather_facts: false
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Setup cloned VM
      ansible.builtin.include_tasks: 06_setup_cloned_vm.yml

    - meta: end_play
