---
name: 'Create ansible-test integration_config.yml'
description: 'Create ansible-test integration_config.yml'
inputs:
  sc_host:  # id of input
    description: 'SC_HOST environ variable'
    required: true
    # default: 'World'
  # Node with IP .50 is our physical node.
  sc_password_50:
    description: 'sc_password variable to access physical nodes'
    required: true
  smb_password:
    description: 'smb_password variable'
    required: true
  working_directory:
    description: 'Path to working directory'
    required: true
  oidc_client_secret:
    description: 'oidc_client_secret'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Creating integration-config.yml for sc_host=${{ inputs.sc_host }}.
      shell: bash
    - run: |
        cd ${{ inputs.working_directory }}
        cat <<EOF >integ_config_vars.yml
        sc_username_50: xlab
        sc_password_50: ${{ inputs.sc_password_50 }}
        smb_username: ;administrator
        smb_password: ${{ inputs.smb_password }}
        smb_server: 10.5.11.39
        smb_share: /cidata
        oidc_client_id: d2298ec0-0596-49d2-9554-840a2fe20603
        oidc_client_secret: ${{ inputs.oidc_client_secret }}
        EOF
        cat integ_config_vars.yml | jinja2 --strict tests/integration/integration_config.yml.j2 > tests/integration/integration_config.yml
        echo "sc_host: ${{ inputs.sc_host }}" >> tests/integration/integration_config.yml
        pwd
        ls -al tests/integration/integration_config.yml
      shell: bash
