---
name: Ansible test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
env:
  NAMESPACE: scale_computing
  COLLECTION_NAME: hypercore
  # ANSIBLE_TEST_PREFER_PODMAN: 1
jobs:
  sanity:
    name: sanity test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          target-python-version: 3.11
          testing-type: sanity

  units:
    name: units ${{ matrix.ansible }}
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - stable-2.14
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Perform units testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          # target-python-version: ${{ matrix.python }}
          testing-type: units
