---
name: Ansible test
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
env:
  NAMESPACE: scale_computing
  COLLECTION_NAME: hypercore
  # ANSIBLE_TEST_PREFER_PODMAN: 1
jobs:
  job1:
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - id: set-matrix
        name: set version_matrix output
        # run: echo "::set-output name=matrix::{\"node\":[10, 12, 14]}"
        run: python .github/workflows/print_ansible_test_matrix.py >> $GITHUB_OUTPUT

  sanity_units:
    needs: job1
    name: ${{ matrix.testing_type }} test ${{ matrix.ansible }}-py${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.job1.outputs.version_matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          target-python-version: ${{ matrix.python }}
          testing-type: ${{ matrix.testing_type }}
