name: CI matrix
on:
  - push
env:
  WORKDIR: /work-dir/ansible_collections/scale_computing/hypercore
jobs:
  matrix-test:
    strategy:
      matrix:
        sc_version: [9.1, 9.2]
    runs-on: [ubuntu-latest]
    container: python:3.10-slim-buster
    env:
      # SC_ALL: ${{ secrets.SC_ALL_91 }}
      SC_VERSION: ${{ matrix.sc_version }}
    steps:
      - run: cat $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo ENV VARS are IND=$IND matrix.sc_version=${{ matrix.sc_version }} SC_VERSION=$SC_VERSION
      - run: pip install pyyaml
      - run: cat .github/sample_data_sc_all.yml | python .github/load_sc_secrets.py >> $GITHUB_ENV
      # use ".", not "source" (bash vs. ubuntu dash)
      - run: echo SC_HOST=$SC_HOST SC_REPLICATION_DEST_HOST=$SC_REPLICATION_DEST_HOST
      - run: cat $GITHUB_ENV
