name: CI tests
on:
  push:
env:
  # ansible-test needs special directory structure.
  # WORKDIR is a subdir of GITHUB_WORKSPACE
  WORKDIR: work-dir/ansible_collections/scale_computing/hypercore
jobs:
  mypy:
    name: Type checks (mypy)
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:1
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
      - run: echo WORKDIR=$WORKDIR
      - run: echo PWD=$PWD
      - name: Run mypy
        run: mypy -p plugins

  docs:
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:1
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: apt install -y git make rsync
      - run: make docs
        env:
          ANSIBLE_COLLECTIONS_PATH: /work-dir
      - run: ls -al docs/build/html

  sanity-test:
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:1
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
        # Same as "make sanity"
        # TODO reuse Makefile
      - run: black -t py38 --check --diff --color plugins tests/unit
      - run: ansible-lint
      - run: flake8 --exclude tests/output/
      - run: ansible-test sanity --local --python 3.10

  units-test:
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:1
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
        # Same as "make units"
        # TODO reuse Makefile
      - run: ansible-test units --local --python 3.10 --coverage
      - run: ansible-test coverage html --requirements
      - run: ansible-test coverage report --omit 'tests/*' --show-missing
