name: CI tests
on:
  - push
env:
  WORKDIR: /work-dir/ansible_collections/scale_computing/hypercore
jobs:


  smb_cleanup:
    runs-on: [self-hosted]
    container: python:3.10-slim-buster
    env:
      SC_HOST: ${{ secrets.SC_HOST }}
      SC_USERNAME: ${{ secrets.SC_USERNAME }}
      SC_PASSWORD: ${{ secrets.SC_PASSWORD }}
      SMB_SERVER: ${{ secrets.SMB_SERVER }}
      SMB_SHARE: ${{ secrets.SMB_SHARE }}
      SMB_USERNAME: ${{ secrets.SMB_USERNAME }}
      SMB_PASSWORD: ${{ secrets.SMB_PASSWORD }}
      ANSIBLE_COLLECTIONS_PATH: /work-dir
    steps:
      - run: apt-get update -y
      - run: apt-get install -y iputils-ping
      - run: ping 127.0.0.1