name: CI tests
on:
  - push
env:
  WORKDIR: /work-dir/ansible_collections/scale_computing/hypercore
jobs:


  smb_cleanup:
    runs-on: [self-hosted]
    container: python:3.10-slim-buster
    env:
      SC_HOST: ${{ secrets.SC_HOST }}
      SC_USERNAME: ${{ secrets.SC_USERNAME }}
      SC_PASSWORD: ${{ secrets.SC_PASSWORD }}
      SMB_SERVER: ${{ secrets.SMB_SERVER }}
      SMB_SHARE: ${{ secrets.SMB_SHARE }}
      SMB_USERNAME: ${{ secrets.SMB_USERNAME }}
      SMB_PASSWORD: ${{ secrets.SMB_PASSWORD }}
      ANSIBLE_COLLECTIONS_PATH: /work-dir
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip3 install -r sanity.requirements -r test.requirements -r docs.requirements
      - run: apt update
      - run: apt install -y git make
      - run: apt install -y smbclient
      - run: apt install -y iputils-ping
      - run: mkdir -p $WORKDIR
      - run: cp -a ./  $WORKDIR
      - run: cd $WORKDIR/tests/integration/cleanup && ./smb_cleanup.sh
      - run: ping -c 4 192.168.1.248
      - run: smbclient -m SMB3 -L 192.168.1.248 -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB3 -L 192.168.1.248 -U administrator Scale2020!
      - run: smbclient -m SMB3 -L $SMB_USERNAME -U administrator Scale2020!
      - run: smbclient -m SMB3 -L $SMB_USERNAME -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB2 -L 192.168.1.248 -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB2 -L 192.168.1.248 -U administrator Scale2020!
      - run: smbclient -m SMB2 -L $SMB_USERNAME -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB2 -L $SMB_USERNAME -U administrator Scale2020!
      - run: smbclient -m SMB1 -L 192.168.1.248 -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB1 -L 192.168.1.248 -U administrator Scale2020!
      - run: smbclient -m SMB1 -L $SMB_USERNAME -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m SMB1 -L $SMB_USERNAME -U administrator Scale2020!
      - run: smbclient -m NT1 -L 192.168.1.248 -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m NT1 -L 192.168.1.248 -U administrator Scale2020!
      - run: smbclient -m NT1 -L $SMB_USERNAME  -U $SMB_USERNAME $SMB_PASSWORD
      - run: smbclient -m NT1 -L $SMB_USERNAME  -U administrator Scale2020!
      - run: smbclient -m SMB3 -L $SMB_SERVER -I 192.168.1.248
      - run: smbclient //$SMB_SERVER$SMB_SHARE -U $SMB_USERNAME $SMB_PASSWORD -N -E
