name: CI tests
on:
  - push
env:
  WORKDIR: /work-dir/ansible_collections/scale_computing/hypercore
jobs:


  smb_cleanup:

    runs-on: [self-hosted]
    container: python:3.10-slim-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: apt update
      - run: apt install -y git make
      - run: apt install -y smbclient
      - run: mkdir -p $WORKDIR
      - run: cp -a ./  $WORKDIR
      - run: cd $WORKDIR/tests/integration/cleanup && ./smb_cleanup.sh ${{ secrets.SMB_SERVER }} ${{ secrets.SMB_SHARE }} "${{ secrets.SMB_USERNAME }}" ${{ secrets.SMB_PASSWORD }}