name: integ-test
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      integ_tests_include:
        type: string
        description: |-
          List integration tests to include.
          Use "*" to run all tests.
          Use regex like 'node|^git_issue' to run only a subset.
        default: ""
      # vm_import|vm_export - they need SMB server
      # dns_config|time_server - NTP cannot be reconfigured if DNS is invalid
      # git_issues - slow, do not run on each push. TODO - run them only once a day
      # oidc_config - during reconfiguration API returns 500/502 errors for other requests
      # smtp - email_alert test requires a configured SMTP
      # role_ - role cluster_config reconfigures DNS, SMTP, OIDC.
      integ_tests_exclude:
        type: string
        description: |-
          List integration tests to exclude.
          Use "*" to exclude all tests.
          Use regex like 'node|^git_issue|^dns_config$' to exclude only a subset.
        default: "^dns_config$|^cluster_shutdown$|^version_update$|^oidc_config$|^smtp$|^role_"
env:
  INTEG_TESTS_INCLUDE_SCHEDULE: "*"
  INTEG_TESTS_EXCLUDE_SCHEDULE: "^dns_config$|^cluster_shutdown$|^version_update$|^oidc_config$|^smtp$|^role_"
  # ansible-test needs special directory structure.
  # WORKDIR is a subdir of GITHUB_WORKSPACE
  WORKDIR: work-dir/ansible_collections/scale_computing/hypercore
# Run only one workflow for specific branch.
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # This should be run at least once before first integration tests run.
  # As long as prepared HC3 host remains prepared, we do not need (except on very first run)
  # to delay integ-test until integration-prepare-env finishes.
  integration-prepare-env:
    runs-on: [self-hosted2]
    container: quay.io/justinc1_github/scale_ci_integ:2
    env:
      ANSIBLE_COLLECTIONS_PATH: $GITHUB_WORKSPACE/work-dir
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: ansible-galaxy collection install community.crypto community.general
      - run: ansible-galaxy collection list
      - uses: ./work-dir/ansible_collections/scale_computing/hypercore/.github/actions/make-integ-config
        with:
          ci_config_all: ${{ vars.CI_CONFIG_HC_IP50 }}
          sc_host: https://10.5.11.200
          sc_username: admin
          sc_password: ${{ secrets.CI_CONFIG_HC_IP200_SC_PASSWORD }}
          smb_password: ${{ secrets.CI_CONFIG_HC_IP50_SMB_PASSWORD }}
          sc_replication_dest_password: ${{ secrets.CI_CONFIG_HC_IP50_SC_REPLICATION_DEST_PASSWORD }}
          working_directory: ${{ env.WORKDIR }}
      - run: ansible-playbook tests/integration/prepare/prepare_iso.yml
      - run: ansible-playbook tests/integration/prepare/prepare_vm.yml
      - run: ansible-playbook tests/integration/prepare/prepare_examples.yml
    if: "${{ github.event.inputs.integ_tests_include || github.event.schedule }}"

  integ-matrix:
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:2
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      # We want to run all integ tests periodically - "integ_tests_include || '*'", the '*' is used.
      # When running with workflow-dispatch, user is required to put some non-empty string into integ_tests_include.
      - run: echo 'INTEG_TESTS_INCLUDE=${{ github.event.inputs.integ_tests_include || env.INTEG_TESTS_INCLUDE_SCHEDULE }}' >> $GITHUB_ENV
      - run: echo 'INTEG_TESTS_EXCLUDE=${{ github.event.inputs.integ_tests_exclude || env.INTEG_TESTS_EXCLUDE_SCHEDULE }}' >> $GITHUB_ENV

      - id: set-matrix
        shell: bash
        run: |-
          echo "matrix=$(
            ls -r tests/integration/targets |
            grep -v -E "${{ env.INTEG_TESTS_EXCLUDE }}" |
            grep -E "${{ env.INTEG_TESTS_INCLUDE }}" |
            jq -R -s -c 'split("\n")[:-1]'
          )" >> $GITHUB_OUTPUT
    if: "${{ github.event.inputs.integ_tests_include || github.event.schedule }}"

  examples-matrix:
    runs-on: [ ubuntu-latest ]
    container: quay.io/justinc1_github/scale_ci_integ:2
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      # A few files are not an example playbook:
      #   hypercore_inventory.yml - inventory example
      #   cloud-init-user-data-example.yml - cloud-init user-data example
      - id: set-matrix
        shell: bash
        run: |-
          echo "matrix=$(
            ls -r examples |
            grep -v -E "^README.md$|^hypercore_inventory.yml$|^cloud-init-user-data-example.yml$" |
            jq -R -s -c 'split("\n")[:-1]'
          )" >> $GITHUB_OUTPUT
    if: "${{ github.event.inputs || github.event.schedule }}"

  examples-run:
    needs:
      - examples-matrix
    runs-on: [ self-hosted2 ]
    container: quay.io/justinc1_github/scale_ci_integ:2
    env:
      ANSIBLE_COLLECTIONS_PATH: $GITHUB_WORKSPACE/work-dir
      DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    strategy:
      fail-fast: false
      matrix:
        ansible: [ 2.13.0 ]
        example_name: ${{ fromJson(needs.examples-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: pip install ansible-core~=${{ matrix.ansible }}
      - run: ansible-galaxy collection install community.crypto community.general
      - run: ansible-galaxy collection list

      # ${{ env.WORKDIR }} cannot be used
      - uses: ./work-dir/ansible_collections/scale_computing/hypercore/.github/actions/make-integ-config
        with:
          ci_config_all: ${{ vars.CI_CONFIG_HC_IP50 }}
          sc_host: https://10.5.11.200
          sc_username: admin
          sc_password: ${{ secrets.CI_CONFIG_HC_IP200_SC_PASSWORD }}
          smb_password: ${{ secrets.CI_CONFIG_HC_IP50_SMB_PASSWORD }}
          sc_replication_dest_password: ${{ secrets.CI_CONFIG_HC_IP50_SC_REPLICATION_DEST_PASSWORD }}
          working_directory: ${{ env.WORKDIR }}
      - run: |
          pwd
          ls -al tests/integration/integration_config.yml
          head tests/integration/integration_config.yml

      - run: |
          eval export SC_HOST=$(cat tests/integration/integration_config.yml | yq '.sc_host')
          eval export SC_USERNAME=$(cat tests/integration/integration_config.yml | yq '.sc_username')
          eval export SC_PASSWORD=$(cat tests/integration/integration_config.yml | yq '.sc_password')
          eval export SC_TIMEOUT=$(cat tests/integration/integration_config.yml | yq '.sc_timeout')
          ansible-playbook -i localhost, -e hypercore_example_check_mode=true examples/${{ matrix.example_name }}

  integ:
    needs:
      - integ-matrix
      # - units-test
    runs-on: [self-hosted2]
    container: quay.io/justinc1_github/scale_ci_integ:2
    env:
      DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    strategy:
      fail-fast: false
      matrix:
        ansible: [2.13.0]
        # python: [3.11]
        # test_name: [user_info]
        test_name: ${{ fromJson(needs.integ-matrix.outputs.matrix) }}
        sc_host:
          - https://10.5.11.200
          - https://10.5.11.201
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: pip install ansible-core~=${{ matrix.ansible }}
      # We have ansible.cfg "for testing" in git repo
      # (it is excluded in galaxy.yml, so it is not part of collection artifact)
      # But it does affect ansible-galaxy and ansible-test commands.
      - run: ansible-galaxy collection install community.crypto
      - run: ansible-galaxy collection list
      # ${{ env.WORKDIR }} cannot be used
      - uses: ./work-dir/ansible_collections/scale_computing/hypercore/.github/actions/make-integ-config
        with:
          ci_config_all: ${{ vars.CI_CONFIG_HC_IP50 }}
          sc_host: ${{ matrix.sc_host }}
          sc_username: admin
          sc_password: ${{ secrets.CI_CONFIG_HC_IP200_SC_PASSWORD }}
          smb_password: ${{ secrets.CI_CONFIG_HC_IP50_SMB_PASSWORD }}
          sc_replication_dest_password: ${{ secrets.CI_CONFIG_HC_IP50_SC_REPLICATION_DEST_PASSWORD }}
          working_directory: ${{ env.WORKDIR }}
      - run: ansible-test integration --local ${{ matrix.test_name }}


  replica_cleanup:
    needs:
      - integ
    runs-on: [self-hosted2]
    container: quay.io/justinc1_github/scale_ci_integ:2
    env:
      ANSIBLE_COLLECTIONS_PATH: $GITHUB_WORKSPACE/work-dir
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      - run: pip install ansible-core~=2.13.0
      # ${{ env.WORKDIR }} cannot be used
      - uses: ./work-dir/ansible_collections/scale_computing/hypercore/.github/actions/make-integ-config
        with:
          ci_config_all: ${{ vars.CI_CONFIG_HC_IP50 }}
          sc_host: https://10.5.11.200
          sc_username: admin
          sc_password: ${{ secrets.CI_CONFIG_HC_IP200_SC_PASSWORD }}
          smb_password: ${{ secrets.CI_CONFIG_HC_IP50_SMB_PASSWORD }}
          sc_replication_dest_password: ${{ secrets.CI_CONFIG_HC_IP50_SC_REPLICATION_DEST_PASSWORD }}
          working_directory: ${{ env.WORKDIR }}
      - run: ansible-galaxy collection install community.general
      - run: ansible-playbook tests/integration/cleanup/ci_replica_cleanup.yml

  smb_cleanup:
    needs:
      - integ
    runs-on: [self-hosted2]
    container: quay.io/justinc1_github/scale_ci_integ:2
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKDIR }}
      # ${{ env.WORKDIR }} cannot be used
      - uses: ./work-dir/ansible_collections/scale_computing/hypercore/.github/actions/make-integ-config
        with:
          ci_config_all: ${{ vars.CI_CONFIG_HC_IP50 }}
          sc_host: https://10.5.11.200
          sc_username: admin
          sc_password: ${{ secrets.CI_CONFIG_HC_IP200_SC_PASSWORD }}
          smb_password: ${{ secrets.CI_CONFIG_HC_IP50_SMB_PASSWORD }}
          sc_replication_dest_password: ${{ secrets.CI_CONFIG_HC_IP50_SC_REPLICATION_DEST_PASSWORD }}
          working_directory: ${{ env.WORKDIR }}
      - run: |
          cd tests/integration/cleanup && ./smb_cleanup.sh \
            "$(cat ../integration_config.yml | yq '.smb_server' | sed -e 's/^"//' -e 's/"$//')" \
            "$(cat ../integration_config.yml | yq '.smb_share' | sed -e 's/^"//' -e 's/"$//')" \
            "$(cat ../integration_config.yml | yq '.smb_username' | sed -e 's/^"//' -e 's/"$//')" \
            "$(cat ../integration_config.yml | yq '.smb_password' | sed -e 's/^"//' -e 's/"$//')"
