---
# from https://github.com/ansible-collections/amazon.aws/
name: changelog and linters

# on: [workflow_call] # allow this workflow to be called from other workflows
on:
  push:
  pull_request:

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox.yml@main
    with:
      envname: ""
      labelname: lint
# 12
