---
name: Release and Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Automation Hub release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v1.6.0
      - name: Build the collection
        run: ansible-galaxy collection build -v --force
      - name: Publish the collection on Automation Hub
        run: |
          set -euo pipefail
          TARBALL=$(ls -1 ./*.tar.gz)

          # cat << EOF > ansible.cfg
          #
          # [galaxy]
          # server_list = rh_automation_hub
          #
          # [galaxy_server.rh_automation_hub]
          # url=$ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_URL
          # auth_url=$ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_AUTH_URL
          # client_id=$ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_CLIENT_ID
          # token=$ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_TOKEN
          #
          # EOF

          ansible-galaxy -vvv collection publish "${TARBALL}"

          # rm ansible.cfg
        env:
          ANSIBLE_GALAXY_SERVER_LIST: rh_automation_hub
          ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_URL: https://console.redhat.com/api/automation-hub/
          ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_CLIENT_ID: de38c20f-fe69-466e-a9bc-21ddf1724cd9
          ANSIBLE_GALAXY_SERVER_RH_AUTOMATION_HUB_TOKEN: ${{ secrets.AUTOMATION_HUB_API_KEY }}
